# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: musicdiary
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: musicdiary_test
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
