-- diary_user
CREATE TABLE IF NOT EXISTS diary_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   is_admin BOOLEAN NOT NULL,
   date_of_birth date NOT NULL,
   bio VARCHAR(255),
   profile_image_url VARCHAR(255),
   CONSTRAINT pk_diaryuser PRIMARY KEY (id)
);

INSERT INTO diary_user (username, email, is_admin, date_of_birth, bio, profile_image_url) VALUES (
  'NeilKinnock1983',
  'kinnock@fake.com',
  true,
  '1942-03-28',
  'I was leader of the labour party',
  'https://upload.wikimedia.org/wikipedia/commons/3/37/Official_portrait_of_Neil_Kinnock%2C_Member_of_the_EC_%28cropped%29.jpg'
);

-- artist
CREATE TABLE artist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   date_of_birth date,
   picture_url VARCHAR(255),
   bio VARCHAR(255),
   CONSTRAINT pk_artist PRIMARY KEY (id)
);

INSERT INTO artist
(name, date_of_birth, picture_url, bio)
VALUES (
  'Tupac Shakur',
  '1971-06-16',
  'https://upload.wikimedia.org/wikipedia/en/b/b5/Tupac_Amaru_Shakur2.jpg',
  'West Coast Rapper'
),
(
  'Biggie Smalls',
  '1972-05-21',
  'https://upload.wikimedia.org/wikipedia/en/5/51/The_Notorious_B.I.G.jpg',
  'East Coast Rapper'
);

-- loggable
CREATE TABLE loggable (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   loggable_type VARCHAR(31),
   submitted_by_id BIGINT NOT NULL,
   title VARCHAR(255),
   song_album_id BIGINT,
   length INTEGER,
   lyrics_url VARCHAR(255),
   album_index INTEGER,
   concert_date date,
   venue VARCHAR(255),
   genre VARCHAR(255),
   release_date date,
   cover_art_url VARCHAR(255),
   CONSTRAINT pk_loggable PRIMARY KEY (id)
);

CREATE TABLE loggable_artist (
  loggable_id BIGINT NOT NULL,
   artists_id BIGINT NOT NULL,
   CONSTRAINT pk_loggable_artist PRIMARY KEY (loggable_id, artists_id)
);

ALTER TABLE loggable ADD CONSTRAINT FK_LOGGABLE_ON_SONG_ALBUM FOREIGN KEY (song_album_id) REFERENCES loggable (id);

ALTER TABLE loggable ADD CONSTRAINT FK_LOGGABLE_ON_SUBMITTED_BY FOREIGN KEY (submitted_by_id) REFERENCES diary_user (id);

ALTER TABLE loggable_artist ADD CONSTRAINT fk_logart_on_artist FOREIGN KEY (artists_id) REFERENCES artist (id);

ALTER TABLE loggable_artist ADD CONSTRAINT fk_logart_on_loggable FOREIGN KEY (loggable_id) REFERENCES loggable (id);

-- set_list_item
CREATE TABLE set_list_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   concert_id BIGINT NOT NULL,
   song_id BIGINT,
   title VARCHAR(255) NOT NULL,
   length INTEGER NOT NULL,
   set_index INTEGER NOT NULL,
   CONSTRAINT pk_setlistitem PRIMARY KEY (id)
);

ALTER TABLE set_list_item ADD CONSTRAINT FK_SETLISTITEM_ON_CONCERT FOREIGN KEY (concert_id) REFERENCES loggable (id);

ALTER TABLE set_list_item ADD CONSTRAINT FK_SETLISTITEM_ON_SONG FOREIGN KEY (song_id) REFERENCES loggable (id);

-- diary_entry
CREATE TABLE diary_entry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   diary_user_id BIGINT NOT NULL,
   loggable_id BIGINT NOT NULL,
   log_date date,
   rating SMALLINT,
   review VARCHAR(255),
   CONSTRAINT pk_diaryentry PRIMARY KEY (id)
);

ALTER TABLE diary_entry ADD CONSTRAINT FK_DIARYENTRY_ON_DIARY_USER FOREIGN KEY (diary_user_id) REFERENCES diary_user (id);

ALTER TABLE diary_entry ADD CONSTRAINT FK_DIARYENTRY_ON_LOGGABLE FOREIGN KEY (loggable_id) REFERENCES loggable (id);

-- diary_list
CREATE TABLE diary_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title VARCHAR(255),
   description VARCHAR(255),
   diary_user_id BIGINT NOT NULL,
   CONSTRAINT pk_diarylist PRIMARY KEY (id)
);

ALTER TABLE diary_list ADD CONSTRAINT FK_DIARYLIST_ON_DIARY_USER FOREIGN KEY (diary_user_id) REFERENCES diary_user (id);

-- diary_list_entry
CREATE TABLE diary_list_entry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   diary_list_id BIGINT NOT NULL,
   loggable_id BIGINT NOT NULL,
   list_index INTEGER NOT NULL,
   note VARCHAR(255),
   CONSTRAINT pk_diarylistentry PRIMARY KEY (id)
);

ALTER TABLE diary_list_entry ADD CONSTRAINT FK_DIARYLISTENTRY_ON_DIARY_LIST FOREIGN KEY (diary_list_id) REFERENCES diary_list (id);

ALTER TABLE diary_list_entry ADD CONSTRAINT FK_DIARYLISTENTRY_ON_LOGGABLE FOREIGN KEY (loggable_id) REFERENCES loggable (id);